language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" -r lambda/requirements.txt # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage