dist: focal
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install libgnutls28-dev
install: "pip install -r lambda/requirements.txt"
script:
  - flake8 lambda
  - coverage run lambda/bak.py
  - pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
